#!/bin/bash

shortcuts=$(grep "^[^[:blank:]]" ~/.config/sxhkd/sxhkdrc | sed 's/^[^#]/\t&/' |sed -e 's/^[#].*/<b>&<\/b>/' | sed 's/#//')
dunstify -a "Environment help" "⌨️ Shortcuts" "<small>$shortcuts</small>" -t 10000 
