#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V 

bspc config border_width         3
bspc config window_gap          12
bspc config focused_border_color "#ffb52a"

bspc config split_ratio          0.5

bspc rule -a Gimp desktop=III state=monocle follow=on
bspc rule -a libreoffice desktop=II follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#run additional components
exec ~/.config/environmentrc
